server:
  port: 8081


dubbo:
  application:
    name: user-provider
  registry:
    address: zookeeper://192.168.21.141:2181

  protocol:
    name: dubbo
    port: 20880
    accesslog: dubbo-access.log
  provider:
    retries: 0
    timeout: 3000
  monitor:
    protocol: registry
  scan: com.z.dubboprovider.serviceImpl

spring:
  datasource:
    url: jdbc:mysql://192.168.21.141:3306/dsm?useUnicode=true&characterEncoding=UTF-8&useSSL=false
    username: root
    password: 1
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
mybatis:
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl